- name: Delete current install dir
  sudo: yes
  shell: rm -rf {{install_dir}}

- name: Ensure {{install_dir}} dir exists
  sudo: yes
  file: path={{install_dir}} state=directory

- name: Unzip kafka
  sudo: yes
  shell: tar xzf {{temp_dir}}/kafka.tgz -C {{install_dir}}
