- name: Add repository key of DataStax
  command: bash -c "curl -L http://debian.datastax.com/debian/repo_key | sudo apt-key add -"

- name: Copy cassandra repo source.list
  sudo: yes
  copy: src=cassandra.sources.list dest=/etc/apt/sources.list.d/cassandra.sources.list
  notify: 
    - update apt cache

- name: Install JNA and Cassandra
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
      - libjna-java
      - cassandra
