- name: Add hadoop group
  sudo: yes
  group: name={{group}} state=present

- name: Add hadoop user
  sudo: yes
  user: name={{user}} group={{group}} home={{install_dir}} shell=/bin/bash

- name: Ensure {{temp_dir}} dir exists
  sudo: yes
  file: path={{temp_dir}} state=directory

- name: Copy install file to server
  sudo: yes
  copy: src={{install_file}} dest={{temp_dir}}/hadoop.tgz

- name: Delete current install dir
  sudo: yes
  shell: rm -rf {{install_dir}}

- name: Ensure {{install_dir}} dir exists
  sudo: yes
  file: path={{install_dir}} state=directory

- name: Unzip install file
  sudo: yes
  shell: tar xzf {{temp_dir}}/hadoop.tgz -C {{install_dir}}  --strip 1

- name: Copy configuration files
  sudo: yes
  template: src={{item}} dest={{install_dir}}/etc/hadoop/{{item}}
  with_items:
    - hadoop-env.sh
    - core-site.xml
    - hdfs-site.xml
    - yarn-site.xml
    - slaves

- name: Create data dirs
  sudo: yes
  file: path={{item}} state=directory
  with_items:
    - "{{data_dir}}/name"
    - "{{data_dir}}/data"

- name: Change the owner of hadoop
  sudo: yes
  file: path={{item}} recurse=yes owner={{user}} group={{group}}
  with_items:
    - "{{install_dir}}"
    - "{{data_dir}}/name"
    - "{{data_dir}}/data"
