- name: Install docker related packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
      - docker.io

- name: Create docker group for docker client user
  sudo: yes
  group: name=docker

- name: Add vagrant user to docker group
  sudo: yes
  user: name=vagrant groups=docker append=yes