- name: Update source list file to sohu
  sudo: yes
  copy: src=sources.list dest=/etc/apt/sources.list

- name: Set local time zone
  sudo: yes
  command: timedatectl set-timezone Asia/Shanghai

# - name: Update apt cache
#   sudo: yes
#   apt: update_cache=yes

- name: Install default packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
      - libpq-dev # Required for Ansible to interact with postgres
      - python-psycopg2 # Required for Ansible to interact with postgres
      - git
      - tree
      - unzip
      